/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PeachButton {
        /**
          * @default 'primary'
         */
        "appearance": 'primary' | 'secondary';
        /**
          * @default 'Click Me'
         */
        "text": string;
    }
}
export interface PeachButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPeachButtonElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPeachButtonElementEventMap {
        "peachClick": void;
    }
    interface HTMLPeachButtonElement extends Components.PeachButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPeachButtonElementEventMap>(type: K, listener: (this: HTMLPeachButtonElement, ev: PeachButtonCustomEvent<HTMLPeachButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPeachButtonElementEventMap>(type: K, listener: (this: HTMLPeachButtonElement, ev: PeachButtonCustomEvent<HTMLPeachButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPeachButtonElement: {
        prototype: HTMLPeachButtonElement;
        new (): HTMLPeachButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "peach-button": HTMLPeachButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PeachButton {
        /**
          * @default 'primary'
         */
        "appearance"?: 'primary' | 'secondary';
        "onPeachClick"?: (event: PeachButtonCustomEvent<void>) => void;
        /**
          * @default 'Click Me'
         */
        "text"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "peach-button": PeachButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "peach-button": LocalJSX.PeachButton & JSXBase.HTMLAttributes<HTMLPeachButtonElement>;
        }
    }
}
