/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
          * @default ''
         */
        "first": string;
        /**
          * The last name
          * @default ''
         */
        "last": string;
        /**
          * The middle name
          * @default ''
         */
        "middle": string;
    }
    interface PeachProductCard {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPeachProductCardElement extends Components.PeachProductCard, HTMLStencilElement {
    }
    var HTMLPeachProductCardElement: {
        prototype: HTMLPeachProductCardElement;
        new (): HTMLPeachProductCardElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "peach-product-card": HTMLPeachProductCardElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
          * @default ''
         */
        "first"?: string;
        /**
          * The last name
          * @default ''
         */
        "last"?: string;
        /**
          * The middle name
          * @default ''
         */
        "middle"?: string;
    }
    interface PeachProductCard {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "peach-product-card": PeachProductCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "peach-product-card": LocalJSX.PeachProductCard & JSXBase.HTMLAttributes<HTMLPeachProductCardElement>;
        }
    }
}
