/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
          * @default ''
         */
        "first": string;
        /**
          * The last name
          * @default ''
         */
        "last": string;
        /**
          * The middle name
          * @default ''
         */
        "middle": string;
    }
    interface PeachProductCard {
        /**
          * The category badge text
          * @default 'Supplement'
         */
        "category": string;
        /**
          * Array of product image URLs
          * @default []
         */
        "images": string[];
        /**
          * Indicates if the product is on sale
          * @default false
         */
        "isSale": boolean;
        /**
          * The price display
          * @default '$0.00'
         */
        "price": string;
        /**
          * The product title
          * @default 'Premium Peach Nutrition'
         */
        "productTitle": string;
    }
}
export interface PeachProductCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPeachProductCardElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPeachProductCardElementEventMap {
        "addToCart": any;
    }
    interface HTMLPeachProductCardElement extends Components.PeachProductCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPeachProductCardElementEventMap>(type: K, listener: (this: HTMLPeachProductCardElement, ev: PeachProductCardCustomEvent<HTMLPeachProductCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPeachProductCardElementEventMap>(type: K, listener: (this: HTMLPeachProductCardElement, ev: PeachProductCardCustomEvent<HTMLPeachProductCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPeachProductCardElement: {
        prototype: HTMLPeachProductCardElement;
        new (): HTMLPeachProductCardElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "peach-product-card": HTMLPeachProductCardElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
          * @default ''
         */
        "first"?: string;
        /**
          * The last name
          * @default ''
         */
        "last"?: string;
        /**
          * The middle name
          * @default ''
         */
        "middle"?: string;
    }
    interface PeachProductCard {
        /**
          * The category badge text
          * @default 'Supplement'
         */
        "category"?: string;
        /**
          * Array of product image URLs
          * @default []
         */
        "images"?: string[];
        /**
          * Indicates if the product is on sale
          * @default false
         */
        "isSale"?: boolean;
        "onAddToCart"?: (event: PeachProductCardCustomEvent<any>) => void;
        /**
          * The price display
          * @default '$0.00'
         */
        "price"?: string;
        /**
          * The product title
          * @default 'Premium Peach Nutrition'
         */
        "productTitle"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "peach-product-card": PeachProductCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "peach-product-card": LocalJSX.PeachProductCard & JSXBase.HTMLAttributes<HTMLPeachProductCardElement>;
        }
    }
}
