/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PeachButton {
        /**
          * Disables the button interaction
          * @default false
         */
        "disabled": boolean;
        /**
          * The visual style of the button
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'outline';
    }
    interface PeachCard {
        /**
          * Optional Badge text (e.g. 'Sale', 'New')
         */
        "badge"?: string;
        /**
          * Currency symbol
          * @default '€'
         */
        "currency": string;
        /**
          * Image source URL
         */
        "imgSrc": string;
        /**
          * Regular Price
         */
        "price": number;
        /**
          * Product Name
         */
        "productName": string;
        /**
          * Optional Sale Price
         */
        "salePrice"?: number;
    }
    interface PeachInput {
        /**
          * The label text above the input
          * @default ''
         */
        "label": string;
        /**
          * The placeholder text
          * @default 'Enter text...'
         */
        "placeholder": string;
        /**
          * The current value
          * @default ''
         */
        "value": string;
    }
    interface PeachStatusBadge {
        /**
          * @default 'Active'
         */
        "label": string;
        /**
          * @default 'success'
         */
        "status": 'success' | 'warning' | 'error';
    }
}
export interface PeachButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPeachButtonElement;
}
export interface PeachInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPeachInputElement;
}
declare global {
    interface HTMLPeachButtonElementEventMap {
        "peachClick": any;
    }
    interface HTMLPeachButtonElement extends Components.PeachButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPeachButtonElementEventMap>(type: K, listener: (this: HTMLPeachButtonElement, ev: PeachButtonCustomEvent<HTMLPeachButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPeachButtonElementEventMap>(type: K, listener: (this: HTMLPeachButtonElement, ev: PeachButtonCustomEvent<HTMLPeachButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPeachButtonElement: {
        prototype: HTMLPeachButtonElement;
        new (): HTMLPeachButtonElement;
    };
    interface HTMLPeachCardElement extends Components.PeachCard, HTMLStencilElement {
    }
    var HTMLPeachCardElement: {
        prototype: HTMLPeachCardElement;
        new (): HTMLPeachCardElement;
    };
    interface HTMLPeachInputElementEventMap {
        "valueChange": string;
    }
    interface HTMLPeachInputElement extends Components.PeachInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPeachInputElementEventMap>(type: K, listener: (this: HTMLPeachInputElement, ev: PeachInputCustomEvent<HTMLPeachInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPeachInputElementEventMap>(type: K, listener: (this: HTMLPeachInputElement, ev: PeachInputCustomEvent<HTMLPeachInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPeachInputElement: {
        prototype: HTMLPeachInputElement;
        new (): HTMLPeachInputElement;
    };
    interface HTMLPeachStatusBadgeElement extends Components.PeachStatusBadge, HTMLStencilElement {
    }
    var HTMLPeachStatusBadgeElement: {
        prototype: HTMLPeachStatusBadgeElement;
        new (): HTMLPeachStatusBadgeElement;
    };
    interface HTMLElementTagNameMap {
        "peach-button": HTMLPeachButtonElement;
        "peach-card": HTMLPeachCardElement;
        "peach-input": HTMLPeachInputElement;
        "peach-status-badge": HTMLPeachStatusBadgeElement;
    }
}
declare namespace LocalJSX {
    interface PeachButton {
        /**
          * Disables the button interaction
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Emitted when the button is clicked
         */
        "onPeachClick"?: (event: PeachButtonCustomEvent<any>) => void;
        /**
          * The visual style of the button
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'outline';
    }
    interface PeachCard {
        /**
          * Optional Badge text (e.g. 'Sale', 'New')
         */
        "badge"?: string;
        /**
          * Currency symbol
          * @default '€'
         */
        "currency"?: string;
        /**
          * Image source URL
         */
        "imgSrc"?: string;
        /**
          * Regular Price
         */
        "price"?: number;
        /**
          * Product Name
         */
        "productName"?: string;
        /**
          * Optional Sale Price
         */
        "salePrice"?: number;
    }
    interface PeachInput {
        /**
          * The label text above the input
          * @default ''
         */
        "label"?: string;
        /**
          * Emitted when the value changes
         */
        "onValueChange"?: (event: PeachInputCustomEvent<string>) => void;
        /**
          * The placeholder text
          * @default 'Enter text...'
         */
        "placeholder"?: string;
        /**
          * The current value
          * @default ''
         */
        "value"?: string;
    }
    interface PeachStatusBadge {
        /**
          * @default 'Active'
         */
        "label"?: string;
        /**
          * @default 'success'
         */
        "status"?: 'success' | 'warning' | 'error';
    }
    interface IntrinsicElements {
        "peach-button": PeachButton;
        "peach-card": PeachCard;
        "peach-input": PeachInput;
        "peach-status-badge": PeachStatusBadge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "peach-button": LocalJSX.PeachButton & JSXBase.HTMLAttributes<HTMLPeachButtonElement>;
            "peach-card": LocalJSX.PeachCard & JSXBase.HTMLAttributes<HTMLPeachCardElement>;
            "peach-input": LocalJSX.PeachInput & JSXBase.HTMLAttributes<HTMLPeachInputElement>;
            "peach-status-badge": LocalJSX.PeachStatusBadge & JSXBase.HTMLAttributes<HTMLPeachStatusBadgeElement>;
        }
    }
}
